### ISSUE TITLE
[US] As a repository owner, I want to have an accurate documentation

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/repo-template#15]
## Tasks:
- [x] Add badges to README
- [ ] Add Actions stuff
- [ ] Add goal + template use
- [ ] Add license
