### ISSUE TITLE
[US] As a repository owner, I want to be able to create a release filled with changelog using GitHub Action

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/repo-template#3]
## Tasks:
- [ ] Find a GitHub Action to create a release
- [ ] Find a GitHub Action to fill the release body with changelogs
- [ ] Create badge to the documentation
