### ISSUE TITLE
[US] As a repository owner, I want to be able to push my Docker image to GitHub Package Registry via GitHub Actions

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/repo-template#5]
## Tasks:
- [x] Create a workflow to build and push Docker image
- [x] Assure the connexion between GitHub Actions and GitHub Package Registry
- [ ] Create badge to the documentation
